### PR TITLE
update to version 2.9

### PR DESCRIPTION
**Pull request by rosset**

### CODE REVIEW

**Comment by stephenl03** [comment]
Looks like tmux had a bugfix release and the latest version is now 2.9a

https://github.com/tmux/tmux/releases/tag/2.9a

**Comment by rosset** [comment]
> Looks like tmux had a bugfix release and the latest version is now 2.9a
> 
> https://github.com/tmux/tmux/releases/tag/2.9a

yes, I already upgraded on Fedora repositories too:
https://koji.fedoraproject.org/koji/packageinfo?packageID=9438

this PR is waiting for ~10 days at this moment, I'm not sure how busy ius admins are.

**Comment by stephenl03** [comment]
The version in this spec file is 2.9. Shouldn’t it be bumped to 2.9a to match the latest version?

**Comment by rosset** [comment]
done

**Comment by rosset** [comment]
@carlwgeorge can you please merge OR discard these commits? thanks.

**Comment by carlwgeorge** [comment]
Hey @rosset!  Thanks for the pull request.  Things have been crazy busy lately.  I'll  go ahead and merge this, but I probably won't get around to building and publishing this till this weekend or early next week.

**Comment by carlwgeorge** [comment]
I've [switched this package to our new CI system](https://github.com/iusrepo/tmux2/commit/49398c215bfa9159acc4f7cd7a35cfa21f9ea47e) (including flattening the directory structure) and [renamed the package to tmux2](https://github.com/iusrepo/tmux2/commit/9e681283f2d594df6c2a5c59087e89a723a5700c).  I've also [synced up miscellaneous things with the Fedora spec file](https://github.com/iusrepo/tmux2/commit/00794f6277ad929e741f64f560d769a305cf32ee), so in the future we should be able to cherry pick commits from Fedora with ease.

tmux2-2.9a-2 is now available from ius-testing on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14).

**Pull request merged**
